export const SET_FILTER_CATEGORY = "SET_FILTER_CATEGORY"
export const SET_FILTER_PRICE = "SET_FILTER_PRICE"

export const SET_OPEN_CART = "SET_OPEN_CART"
export const SET_ADD_PRODUCT_CART = "SET_ADD_PRODUCT_CART"
export const SET_CLEAR_PRODUCT_CART = "SET_CLEAR_PRODUCT_CART"
